sim_input_dir: "input/data"
sim_res_dir: "results/sim"
input_dir: "results/sim/sim_data"
res_dir: "results/sim/sim_results"
scratch_dir: "results/sim/scratch"

n_iter: 1

n_pos_vals: [20]
# params to toggle: prop_effect, variant variance, position effect, cell count size, variant replicate overdsp, read count overdsp, number of bins
# params: ["none", "n_variants", "effect_prop", "measurement_variance", "position_effect", "cell_count_factor", "variant_phi", "n_reads", "reads_phi", "n_bins", "gate_offset"]
# param_vals: [[0], 
#   [5, 10, 15, 20, 30], # n variants
#   [0.1, 0.3, 0.5, 0.8], # effect prop
#   [0.01, 0.03, 0.05, 0.1, 0.3], # measurement variance
#   [0, 0.1, 0.3, 0.5, 0.8], # pos effect
#   [100, 200, 500], # cell count factor
#   [3, 5, 10, 25, 50, 100, 150], # variant phi
#   [1000000, 5000000, 10000000, 25000000], # num reads
#   [500, 1000, 2500, 5000, 7500, 10000, 20000], # reads phi
#   [2, 3, 4, 8, 16], # num bins
#   [1, 2, 3]] # gates offset from 25% quantiles on log normal scale 

# params: ["none"]
# param_vals: [[0]]
params: ["gate_offset"]
param_vals: [[3]]
datasets: ['gpcr_ph55_20pos']
models: ['FACS_double_sample_repq']
methods: ['enrich2', 'ML', 'MoM', 'weight_mean']

# model stuff
selfphi: False # use own synonymous as phi estimate instead of baseline
SHELL: "zsh"
RCFILE: ".zshrc"